# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build python
        run: cd  3.8.5/opensuse/leap/ && bash build-all.sh
      - name: Upload Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ./bins/*.gz
          tag: false
          draft: false